<?php require_once('./templates/header.phtml');?>

    <h1> Juegos de <?= $name_distributor->nombre?></h1>

    <figure>
        <img src="<?= $name_distributor->imagen?>">
    </figure>
    <div>
        <ul>
            <?php if ($game_distributor):?>
                <?php foreach($game_distributor as $games):?>
                    <li> <strong><?=$games->titulo?></strong> (<?=$games->fecha_salida?>)</li>
                <?php endforeach;?>
            <?php else:?>
                <h2>Esta distribuidora no tiene juegos registrados</h2>
            <?php endif;?>
        </ul>
    </div>