<?php require_once('./templates/header.phtml'); ?>

    <div class="form_distributor">
        <h2>Formulario Distribuidoras</h2>
        <?php if ($formAction=='edit'):?>
            <form action="actualizarDistribuidora/<?= $game->id?>" method="POST">
        <?php else: ?>
            <form action="añadirDistribuidora" method="POST">
        <?php endif; ?>
            <label for="name">Nombre:</label>
            <input type="text" name="name">
            <label for="foundation_year">Fundacion:</label>
            <input type="number" name="foundation_year">
            <label for="headquarters">Pais sede:</label>
            <input type="text" name="headquarters">
            <label for="web">Sitio web</label>
            <input type="text" name="web">

            <button type="submit" id="btn-distributors">Añadir</button>
        </form>   
    </div>