<?php require_once('./templates/header.phtml'); ?>

<h1>Actualizar</h1>
    <div class="form_update_distributor">
        <h2>Distribuidoras</h2>

        <form action="añadirDistribuidora" method="POST">
            <label for="name">Nombre:</label>
            <input type="text" name="name">
            <label for="foundation_year">Fundacion:</label>
            <input type="number" name="foundation_year">
            <label for="headquarters">Sede:</label>
            <input type="text" name="headquarters">
            <label for="web">Sitio web</label>
            <input type="text" name="web">

            <button type="submit" id="btn-distributors">Añadir</button>
        </form>
    </div>
<?php require_once('./templates/footer.phtml'); ?>