<?php require_once('./templates/header.phtml'); ?>

<?php $currentYear = date("Y");?>


    <div class="form_game">
        <h2>Formulario de Juegos</h2>
        <form action="<?= $formAction == 'edit' ? 'actualizarJuego/' . $game->id : 'añadirJuego' ?>" method="POST">
            <label for="title">Titulo del juego:</label>
            <input type="text" name="title" <?= $formAction == 'edit' ? 'value="' . $game->titulo . '"' : '' ?>>

            <label for="genre">Genero:</label>
            <input type="text" name="genre" <?= $formAction == 'edit' ? 'value="' . $game->genero . '"' : '' ?>>

            <label for="distributor">Distribuidora:</label>

            <select name="distributor">
                <?php foreach($distributors as $distributor): ?>
                    <option value="<?= $distributor->id ?>" <?= $formAction == 'edit' && $distributor->id == $game->id_distribuidora ? "selected" : "" ?>>
                        <?= $distributor->nombre ?>
                    </option>
                <?php endforeach; ?>
            </select>

            <label for="launch_date">Año de lanzamiento:</label>
            <input type="number" name="launch_date" min="1901" max="<?= $currentYear?>" <?= $formAction == 'edit' ? 'value="' . $game->fecha_salida . '"' : '' ?>>

            <label for="price">Precio:</label>
            <input type="number" step="any" name="price" <?= $formAction == 'edit' ? 'value="' . $game->precio . '"' : '' ?>>

            <button class="btn-send" type="submit" id="btn-games"><?= $formAction == 'edit' ? 'Editar' : 'Añadir' ?></button>
        </form>
        <?php if($formAction == 'edit'):?>
            <a href="<?= BASE_URL; ?>/administracion"><button class="btn-cancel">Cancelar</button></a>
        <?php endif; ?>
    </div>