<?php require_once('./templates/header.phtml'); ?>
<h1> Juegos </h1>
    <ul>
        <?php if(!empty($this->user->user)): ?>
            <?php foreach($games as $game): ?>
                <li> Nombre: <?=$game->titulo?> | Año: <?=$game->fecha_salida?> | Precio: $<?=$game->precio?></li>
                <a href="juegos/<?= $game->id?>"><button type="submit" id="btn">⬆Ver juego⬆</button></a>
                <a href="eliminarJuego/<?= $game->id?>"><button type="submit" id="btn">✘Eliminar✘</button></a>
                <a href="editarJuego/<?= $game->id?>"><button type="submit" id="btn">⟳Modificar⟳</button></a>
            <?php endforeach; ?>
        <?php else:?>
            <?php foreach($games as $game): ?>
                <li> Nombre: <?=$game->titulo?> | Año: <?=$game->fecha_salida?> | Precio: $<?=$game->precio?></li>
                <a href="juegos/<?= $game->id?>"><button type="submit" id="btn">⬆Ver juego⬆</button></a>
            <?php endforeach;?>
        <?php endif;?>
    </ul>