<?php require_once('./templates/header.phtml'); ?>
<h1> Juegos </h1>
    <ul>
        <?php if(!empty($this->user->user)): ?>
            <?php foreach($games as $game): ?>
                <li><?=$game->titulo?> (<?=$game->fecha_salida?>) | Precio: $<?=$game->precio?></li>
                <a href="juegos/<?= $game->id?>"><button class="btn-view" type="submit">⬆Ver juego⬆</button></a>
                <a href="eliminarJuego/<?= $game->id?>"><button class="btn-delete" type="submit">✘Eliminar✘</button></a>
                <a href="editarJuego/<?= $game->id?>"><button class="btn-edit" type="submit">⟳Modificar⟳</button></a>
            <?php endforeach; ?>
        <?php else:?>
            <?php foreach($games as $game): ?>
                <li><?=$game->titulo?> (<?=$game->fecha_salida?>) | Precio: $<?=$game->precio?></li>
                <a href="juegos/<?= $game->id?>"><button class="btn-view" type="submit">⬆Ver juego⬆</button></a>
            <?php endforeach;?>
        <?php endif;?>
    </ul>