<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Claves Robadas</title>
    <link rel="stylesheet" href="<?= BASE_URL;?>/css/style.css">
    <base href="<?= BASE_URL ?>">
</head>
<body>
    <header>
        <h1>Claves robadas</h1>
        <nav>
            <ul>
                <li><a href="principal">Ver listas</a></li>
                <li><a href="juegos">Lista de juegos</a></li>
                <li><a href="distribuidoras">Lista de distribuidoras</a></li>
                <li><a href="iniciarSesion">Iniciar sesion</a></li>
                <?php if(!empty($this->user->user)): ?>
                    <li><a href="administracion">Administracion</a></li>
                    <li><a href="cerrarSesion">Cerrar sesion</a></li>
                <?php endif; ?>
            </ul>
        </nav>
    </header>
    <main>