<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jueguitos Robados</title>
</head>
<body>
    <header>
        <h1>Jueguitos robados</h1>
        <nav>
            <ul>
                <li><a href= '<?php BASE_URL ?>/verLista' >Ver listas</a></li>
                <li><a href="../juegos">Lista de juegos</a></li>
                <li><a href="../distribuidoras">Lista de distribuidoras</a></li>
            </ul>
        </nav>
    </header>
    <main>